### ISSUE TITLE
child name requirement

### ISSUE THREAD

**Issue by visr** [geoarrow/geoarrow#30]
Hi all, I was working on writing GeoArrow files using [Arrow.jl](https://github.com/apache/arrow-julia) based on the spec here. It worked, though I haven't packaged up the code yet. But I do have some questions if I may!

In https://github.com/geoarrow/geoarrow/blob/f2eb98e7e2f60e/format.md#format it mentions:

> "The child name of ... list should be "vertices/rings/points/rings/linestrings/polygons"."

I didn't add these because Arrow.jl doesn't support setting these names yet, but this was fine for GDAL. That made me wonder, do we need these names at all? It seems to me that this spec set through `ARROW:extension:name` already determines which list is which.

Should I interpret SHOULD here as in https://www.rfc-editor.org/rfc/rfc2119 like the GeoJSON spec?
That would mean that it is ok for an implementation to ignore these names, right?
Are they meant just as a reminder of what is what for developers working with these types?
Or should we leave this name requirement out of the spec, or explicitly state that they can be anything?

Note: I'm not talking about the point field names here, which was brought up in bullet 2 and 4 in https://github.com/geoarrow/geoarrow/pull/26#issue-1378316418.

**Comment by jorisvandenbossche** [comment]
> Hi all, I was working on writing GeoArrow files using [Arrow.jl](https://github.com/apache/arrow-julia) based on the spec here. It worked, though I haven't packaged up the code yet. But I do have some questions if I may!

Cool! And you may certainly ask some questions, this is the place to be ;)

> do we need these names at all?

That's a good question. Purely for the memory layout, we don't need them. But because Arrow (in general, but depending on your bindings of course) allows to name those child arrays, we thought to give them informative names. 

I think at some point we also thought that this could make it so that each geometry type's arrow array would be fully determined by its data type, even if you don't have (or eg lost) the extension name. 

On the other hand, your are correct that the extension name should ensure we always know what kind of geometry data we have. 
And while the Arrow C++ implementation supports custom names of the list childs, there are also some questions on how robust this is (eg will it always be preserved in operations, are those taken into account for checking the equality of two types? -> https://issues.apache.org/jira/browse/ARROW-14999). 
In that linked JIRA, @paleolimbot also mentions:

> In practice the prototype I wrote mostly ignores the list child names, with the exception being the name of a point array which conveys its dimension (e.g., xy, xyz, xym, or xyzm). Conveying the dimension of the point array using the name was done in part to avoid a parser (to parse extension type metadata since it has to be valid utf8) when writing C kernels (since 'name' at the C data array level is just a null-terminated string). At the time we designed this there was no indication that the roundtripping of the child name would be an issue; however, we could certainly work around it.

And certainly if other Arrow implementations might not all support custom list field names, that's another indication we should be flexible on this topic.

So I would think we can indeed formulate that as a "SHOULD". And should we then also say that implementors "MUST" (?) be able to ingest arrays with other names?

**Comment by visr** [comment]
Thanks for the answer. Indeed since we have to give a name it makes sense to suggest to give descriptive ones.

> So I would think we can indeed formulate that as a "SHOULD". And should we then also say that implementors "MUST" (?) be able to ingest arrays with other names?

I'd agree with this SHOULD/MUST approach. It should be noted that if we go down this road it's hard to go back to MUST/MUST. I can prepare a PR.

Since you quoted @paleolimbot on the point names:

>  (e.g., xy, xyz, xym, or xyzm)

The spec currently states:

> the field name of the list should be "xy", "xyz" or "xyzm"

Based on the spec I thought that `n_dim` directly implies the interpretation, e.g. 1: x, 2: xy, 3: xyz. 4: xyzm. But @paleolimbot also mentions `xym`. Is that also allowed? If so perhaps we should add it. I see WKT also has `xym` (Point M). If we have both `xyz` and `xym` that would be the only case where the field name would help the interpretation right, since both at `geoarrow.point`.

**Comment by visr** [comment]
I created #31, hoping to add your clarifications to the spec in a concise manner.

> I think that it's reasonable to allow implementations to assume a coordinate array that is a FixedSizeList with a fixed size of 2 is xy, a fixed size of 3 is xyz, and a fixed size of 4 is xyzm.

This also sounds reasonable to me, but I didn't add this explicitly in #31. If a parser ignores the field names of a `xym` point, and interprets it as `xyz` based on dimensionality, and then writes it using the name `xyz`, this information will be lost.
